---
- name: Play A
  hosts: localhost
  gather_facts: false
  vars:
    device_type: "Router"
    devices: 
      - "R1"
      - "R2"
      - "R3"
    device_creds: 
      user_name: "admin"
      password: "ansible"

      
        

  tasks: #syntax
    - name:  "1010 - OUTPUT DEVICE TYPE"
      debug: #keyword just lika a print statement
        var: device_type

    - name: "1020 - OUTPUT DEVICE DATA"
      debug :            
        var: devices

    - name: "1030 - OUTPUT DEVICE CREDS"
      debug:
        var: device_creds
       

      
